### ISSUE TITLE
⚠️ Backoffice API has degraded performance

### ISSUE THREAD

**Issue by rbudiharso** [usetada/status-page#5]
In [`463b935`](https://github.com/usetada/status-page/commit/463b93531fb7957fb0e959d79215a84811f046a7
), Backoffice API ($BACKOFFICE_API_URL) experienced **degraded performance**:
- HTTP code: 200
- Response time: 1695 ms

**Comment by djrahar** [comment]
Investigating: testing

**Comment by rbudiharso** [comment]
**Resolved:** Backoffice API performance has improved in [`8ab1fbf`](https://github.com/usetada/status-page/commit/8ab1fbff4c43fe11f74fff85902ef6771db77ba9
).
