### ISSUE TITLE
🛑 Evoucher API is down

### ISSUE THREAD

**Issue by rbudiharso** [usetada/status-page#8]
In [`536bfd4`](https://github.com/usetada/status-page/commit/536bfd4f252178f22f19ef193b256b6d7cbcffb9
), Evoucher API ($EGIFT_API_URL) was **down**:
- HTTP code: 503
- Response time: 890 ms

**Comment by djrahar** [comment]
This is not a downtime, One of the Instance was terminated and switch to new one. but the Status check still went to the old instance.
